
language: node_js
node_js: "12.16.1"
cache: npm
before_install: cd travlpak
install: npm ci
before_script:
script: CI=false npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: travlpak/build
  on:
    branch: master
