language: node_js
node_js: -11.6.0
cache: npm
before_install:
install:
  - npm ci
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages
